### ISSUE TITLE
[Suggestion] Create config file  to download Include Files remotely. 

### ISSUE THREAD

**Issue by TandelK** [Sarrus1/sourcepawn-vscode#101]
## Feature description

What do you want to see added to the extension?
We can have one file that can be added in our project that can say that what all things it does require for compiling . 

For eg. i am using Get5 plugin by Splewis but the issue i face right now is that i have to manually download the required extensions as well as include files from different repo just for building latest updated repo and test it out on my server. It requires SteamWorks Include file as well as SM-JSON Include which are both available at Github paths. For his project he is using some file called travis.yml to compile it with automation. This tool can automatically download the required files and than compile the plugin automatically and test for issues or errors. 

https://github.com/splewis/get5/blob/master/.travis.yml

How would it help you?

It will make automation easier for everyone as they have to only update a single file for requirements for compiling the project with proper method. 

How often would you use this feature?
Mostly everytime there will be update for the plugin or making own changes to the project.

**Comment by Sarrus1** [comment]
The travis.yml file allows to run code as GitHub Actions, so this is not applicable to the extension.

However, I planned on having a sort of repo file which would allow to download missing dependencies automatically. Is that what you're suggesting?

**Comment by TandelK** [comment]
Kind of what python projects have requirements.txt files where you can define what all files are required to run or compile the project.

**Comment by Sarrus1** [comment]
But the extension could just look at all the includes in the .sp files and download the correct ones?

**Comment by TandelK** [comment]
But they wont have direct links to original file because if there are any update to those includes than it will be useless.

**Comment by Sarrus1** [comment]
I've decided to go ahead and not implement this, as git already has support for symlinks, and the extension now supports them.
They allow you to achieve exactly what you want, example [here](https://github.com/zer0k-z/gokz-discord) in .gitmodule.
