### ISSUE TITLE
Problem compiling with hotkey

### ISSUE THREAD

**Issue by dran1x** [Sarrus1/sourcepawn-vscode#11]
### Extension Version
`1.10.1` ~ Latest

### User Settings.json
```
{
    "sourcepawnLanguageServer.sourcemod_home": "C:\\Data\\path\\include",
    "sourcepawnLanguageServer.spcomp_path": "C:\\Data\\path\\spcomp.exe",
    "sourcepawnLanguageServer.trace.server": "verbose",
    "sourcepawnLanguageServer.author_name": "DRANIX",
    "sourcepawnLanguageServer.github_name": "dran1x",
    "workbench.iconTheme": "sourcepawn"

}
```

### Workspace Settings.json
```
{
    "sourcepawnLanguageServer.main_path": "C:\\Users\\DRANIX\\Documents\\SourceMod\\csfire.gg\\Experimental\\csfire_skins\\scripting\\csfire_skins.sp"
}
```

### Problem
When trying to compile sourcepawn files with the extension's hotkey, a command error pops up instead of the terminal. On the other hand, when you compile with the button, everything compiles well.

`Compile with hotkey`
![image](https://user-images.githubusercontent.com/48390633/113504560-e6d51a00-9506-11eb-921e-a3893650ab95.png)

**Comment by Sarrus1** [comment]
Thanks for letting me know, this has been fixed and will be published in the next release.
