### ISSUE TITLE
[Suggestion] Expand outlining features

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#115]
## Feature description

Right now, outlining seems to only include functions.
It would be nice to have outlines for defines, variable and enum declarations.

**Comment by Sarrus1** [comment]
As of v2.3.0, the supported code blocks in the outline are:
- Functions (even natives)
- MethodMaps
- Enums
- EnumStructs
- Properties
- Methods

MethodMaps and EnumStructs support nested objects (properties and methods) as well.

I won't implement defines in the outline, as the TypeScript and the C/C++ extension don't do it either, same thing for variables.
I think it will come out as too much information in the outline.

**Comment by zer0k-z** [comment]
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/61156310/133516226-7ac65f91-2159-49ee-b7b9-95ccce58ccc4.png)
C and C++ definitely does it, here's some examples.

**Comment by Sarrus1** [comment]
Oh, didn't know that
Will try to implement it then!

**Comment by Sarrus1** [comment]
Implemented in #119.
