### ISSUE TITLE
[Suggestion] Auto-update bug report template

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#116]
## Feature description

Right now I have to manually change the version of vscode and extension even though I (and maybe most people?) almost always use the latest version. It would be nice to not have to do that.

**Comment by Sarrus1** [comment]
AFAIK there is no way to automatically update the template, other than some twisted workflow, so I'll just switch it to "Latest", as, like you said, everybody uses the latest versions.

**Comment by zer0k-z** [comment]
Yeah, workflow would have to fetch vscode repo's latest tag and your tag as well.
