### ISSUE TITLE
VSCode is "unable to resolve resource"

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#13]
This happens when I click on an error/warning.

I tried using a blank folder, and the "SM Create Project" option, all of them return the same error in the bottom right.
![image](https://user-images.githubusercontent.com/61156310/113577828-2e03fd80-9622-11eb-80ff-65f2a13e12a0.png)

**Comment by Sarrus1** [comment]
This has been solved over Discord:

TL;DR make sure your paths are correct in your settings.json file

**Comment by zer0k-z** [comment]
Also VSCode seems to require a restart for the changes to take effect, if anyone still has the issue after modifying the settings.

**Comment by RezaYaghoubi** [comment]
ss://YWVzLTI1Ni1jZmI6dTFyUldUc3NOdjBw@198.199.101.12:8388
ss://YWVzLTI1Ni1jZmI6dTFyUldUc3NOdjBw@198.199.101.152:8388
