### ISSUE TITLE
Project: SM Create Project 

### ISSUE THREAD

**Issue by leon12171** [Sarrus1/sourcepawn-vscode#15]
hello, until the very last moment I can’t figure this out. Are there any detailed instructions for using this resolution?
![image](https://user-images.githubusercontent.com/24985843/114071198-8993ec80-98a9-11eb-9ead-52b22abcfebd.png)
![image](https://user-images.githubusercontent.com/24985843/114071228-90226400-98a9-11eb-87f3-ef85aeff1c48.png)
![image](https://user-images.githubusercontent.com/24985843/114071369-b516d700-98a9-11eb-9795-6a747d4f17fd.png)

**Comment by Sarrus1** [comment]
Hello, it looks like you're using an old version of the extension, try to use the latest version.

**Comment by leon12171** [comment]
> Hello, it looks like you're using an old version of the extension, try to use the latest version.

![image](https://user-images.githubusercontent.com/24985843/114073958-89e1b700-98ac-11eb-91c6-0037d2396674.png)

Checked the information, and it seems like I'm using the latest version

**Comment by Sarrus1** [comment]
Ok so I had the same problem on the latest build, for some reason the extension didn't bundled correctly, not sure why. If you update to v1.10.4, everything should work again, please let me know if it does 👍

**Comment by Sarrus1** [comment]
Confirmed with another person that the hotfix works

**Comment by kinsi55** [comment]
Could it be that stuff is broken again? Just switched to this from the original and I get the same error when trying to compile - Additionally the ext doesnt seem to work at all as I dont get any autocompletition etc.

**Comment by Sarrus1** [comment]
> ```
> [2021-04-10 04:56:51.113] [exthost] [error] TypeError: Cannot read property '0' of undefined
> 	at activate (...\sarrus.sourcepawn-vscode-1.10.5\client\out\smIndex.js:22:54)
> ```

Please make sure you open the folder containing the .sp file and not the .sp file directly, otherwise the extension won't be able to load. This error means that the extension couldn't find the root folder of your workspace.

**Comment by kinsi55** [comment]
Why should that be a requirement tho? You can get the directory of the edited file and just use that - And you have a null check on `vscode.workspace.workspaceFolders[0]`, you're just not checking if `vscode.workspace` is undefined as well.

But like I said, changing that did not fix the compiler issue.

**Comment by Sarrus1** [comment]
It shouldn't be a requirement, I just didn't get around to implement it yet, this will be fixed in a future release (the next one hopefully)

I'm not sure what's going on with the compile bug on the other hand...

As a workaround, you can generate a task file and use ctrl+shift+b to compile, or you can rollback to a previous version of the extension.

**Comment by leon12171** [comment]
It would be nice to do this when a compilation error highlighted the code in which the error was

**Comment by Sarrus1** [comment]
But if this already works with Error Lens why replicate it in this extension?

**Comment by leon12171** [comment]
Not everyone knows about this resolution, so it would be nice to implement it

**Comment by Sarrus1** [comment]
For sure, but I'd rather have a stable version than introducing features that might break the extension, and which are already available

**Comment by leon12171** [comment]
![image](https://user-images.githubusercontent.com/24985843/115152218-e72df300-a078-11eb-88c2-de8a341be19a.png)

**Comment by Sarrus1** [comment]
Make sure you use a relative path, not an absolute path.
The next release will support both.
