### ISSUE TITLE
Incorrect completion commits

### ISSUE THREAD

**Issue by Sarrus1** [Sarrus1/sourcepawn-vscode#164]
## Basic info

- **OS:** [Any]
- **VSCode version:** Latest
- **Extension version:** Latest

## Further Information

When creating a new variable/function, if inserting parenthesis, it autocompletes to another item.

This is due to #162 .

![Image](https://cdn.discordapp.com/attachments/828084502319595563/925155985176268860/unknown.png)

**Comment by Sarrus1** [comment]
@BoomShotKapow 👀

**Comment by dran1x** [comment]
Love it

**Comment by BoomShotKapow** [comment]
I'll look into it now, my apologies.
