### ISSUE TITLE
Refresh Plugins After Compile

### ISSUE THREAD

**Issue by repository** [Sarrus1/sourcepawn-vscode#167]
## Feature description

I use a local CS:GO server during development instead of a remote one, so I have the compiler output to the plugins folder instead of uploading to an FTP server.
It would be useful to be able to refresh the server after compile instead of upload.

![image](https://user-images.githubusercontent.com/41586666/147513668-dc0dba13-c3ad-473a-a097-3d8b5f6cb5cd.png)
Perhaps you could change this option to "Automatically Refresh Server Plugins After", with the options
 - disabled
 - afterCompile
 - afterUpload

**Comment by dran1x** [comment]
This is a good idea.

**Comment by Sarrus1** [comment]
Implemented in 4bb7593224373c7e8473a3428f5c5dfb582f9d01.
