### ISSUE TITLE
Add define highlighting in pre-compiler checks

### ISSUE THREAD

**Issue by Sarrus1** [Sarrus1/sourcepawn-vscode#168]
## Feature description

![Example](https://cdn.discordapp.com/attachments/831994555263221810/925639890694185020/unknown.png)

**Comment by Sarrus1** [comment]
Seems to be working on v3.0.2, waiting for confirmation from @dran1x.


<img width="481" alt="Capture d’écran 2021-12-30 à 00 37 14" src="https://user-images.githubusercontent.com/63302440/147710800-7555fd1b-f879-4767-be6d-0fa9f514480d.png">

**Comment by dran1x** [comment]
It does highlight elsewhere, and I don't have any themes enabled whatsoever.

![image](https://user-images.githubusercontent.com/48390633/147785175-c25f3aa6-0890-4390-9c6d-3f1f2a8511cb.png)

**Comment by Sarrus1** [comment]
After some testing, it appears that the parser ignores defines when they don't store a variable.
It would also be good to add textmate support for the `#if defined FOO` check.
