### ISSUE TITLE
Improve textmate support for themes other than the default theme

### ISSUE THREAD

**Issue by Sarrus1** [Sarrus1/sourcepawn-vscode#169]

**Comment by dran1x** [comment]
I'm using https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai

**Comment by Sarrus1** [comment]
Unfortunately, this theme (and a lot of other themes it seems), don't support semantic highlighting (which is responsible for highlighting defines and enum members).
See [this issue](https://github.com/azemoh/vscode-one-monokai/issues/41) for example.
