### ISSUE TITLE
Support methodmap autocomplete when declared in an enum.

### ISSUE THREAD

**Issue by caxanga334** [Sarrus1/sourcepawn-vscode#170]
## Basic info

- **OS:** Windows 10
- **VSCode version:** 1.63.2
- **Extension version:** 3.0.1

## Further Information

[I made a video showing this](https://youtu.be/j00BSLwrUBk).
[Enum & Methmodmap declaration](https://github.com/TF2-DMB/CBaseNPC/blob/master/scripting/include/cbasenpc/nav.inc#L70).

## To Reproduce

Steps to reproduce the behaviour:

1. Get the [CBaseNPC](https://github.com/TF2-DMB/CBaseNPC) includes.
2. Try to use **TheNavMesh**.

## Expected behaviour

Autocomplete to appear.

## Error messages

None.

**Comment by Sarrus1** [comment]
Hi, thanks for reporting this.

Just to be sure, the autocompletion is supposed to display everything just as if it was the variable you declared in the second part of the video?

**Comment by caxanga334** [comment]
`Just to be sure, the autocompletion is supposed to display everything just as if it was the variable you declared in the second part of the video?`

Yes.
