### ISSUE TITLE
SAMP .pwn support

### ISSUE THREAD

**Issue by Oliver-Patterson** [Sarrus1/sourcepawn-vscode#172]
### What do you want to see added to the extension?
Not enough support for SAMP, it is possible to implement?
You can specify a "sourcepawn" language for the .pwn file, it works, but seems incomplete.
I don't know if it's an extension bug or a language feature, but the variables in enum that are specified with type are not defined correctly. Suppose:
```
enum e_OBJECT_ATTACH
{
	modelid,
	Float:fOffsetX,
	Float:fOffsetY,
	Float:fOffsetZ,
	Float:fRotX,
	Float:fRotY,
	Float:fRotZ,
	Float:fScaleX,
	Float:fScaleY,
	Float:fScaleZ
}
```
We get something like that in the "outline:
![image](https://user-images.githubusercontent.com/78804737/147953616-0d0ac498-9e2c-46d0-b849-dc307108ce3f.png)
And because of this autocomplete does not work properly.

Also, functions that have a forward in include are not displayed in outline.

### How would it help you?
Well from the obvious, it will make writing code easier.

### How often would you use this feature?
Often.

**Comment by Sarrus1** [comment]
Hi, this extension aims to support Sourcepawn only, but it could be easily adapted to support Pawn, as both language are similar.

I won't add support for SAMP in this extension as it could interfere with SourcePawn features and I am not familiar with Pawn at all.

You can always fork the extension and make some quick changes to support the features you are refering to.
