### ISSUE TITLE
Malformed code outline in certain situations

### ISSUE THREAD

**Issue by bakapear** [Sarrus1/sourcepawn-vscode#179]
## Basic info

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

## Further Information
<details>
<summary>Variables get added from a string if the functions are inside a block</summary>

![image](https://user-images.githubusercontent.com/13366049/148385411-5328d822-6584-49ea-9430-d76997f76363.png)
![image](https://user-images.githubusercontent.com/13366049/148384976-2eb2acf0-65c3-4b1b-bfdb-7fbaafcb0214.png)
</details>
<details>
<summary>Adding an apostrophe or quotation marks to the string makes the entire outline for both functions disappear</summary>

![image](https://user-images.githubusercontent.com/13366049/148384763-6bdd7280-627c-4c0e-a5da-042eca2f4d3d.png)
</details>
<details>
<summary>Moving function code into one line makes it disappear from outline</summary>

![image](https://user-images.githubusercontent.com/13366049/148385268-312d397a-baf9-42de-8b7f-a33e88157e46.png)
</details>

**Comment by Sarrus1** [comment]
1. Due to [this line](https://github.com/Sarrus1/sourcepawn-vscode/blob/8e94835a43ac185772e645780b2dc4954633a1af/src/Parser/readFunction.ts#L51). It should be a `.include`.

**Comment by Sarrus1** [comment]
I will fix `3` in a cleaner implementation of the parser.
