### ISSUE TITLE
Settings require full path?

### ISSUE THREAD

**Issue by r9vRM** [Sarrus1/sourcepawn-vscode#18]
Not sure if this an issue with VScode or your extension but if I use a custom setting or have a root directory it will say that the compiler is not found and I would need to set the path.

Custom setting:
![image](https://user-images.githubusercontent.com/75724044/114671956-7b830900-9cb9-11eb-9236-f954fb54c697.png)
Works with tasks.json (I use it for my compile task)
![image](https://user-images.githubusercontent.com/75724044/114672517-15e34c80-9cba-11eb-9296-dc8cc553baac.png)
Root directory:
![image](https://user-images.githubusercontent.com/75724044/114672777-5cd14200-9cba-11eb-9b3c-db76fb5dd92a.png)

Even better: have a setting to enable/disable linter completely and/or an array of file names for enable/disable without having to add `//linter=false` everytime

Thanks for updating the extension!

**Comment by Sarrus1** [comment]
As far I as know, what you're doing with `${sourcemodDir}` won't work from the config because the extension isn't aware that this is a placeholder which should be replaced.

That being said, I need to test this myself to be sure.

Regarding the linter, yes that would be great, will do that 👍

**Comment by Sarrus1** [comment]
I've implemented the linter disable option in 1.10.6.

Also, I can confirm that VSCode does not support placeholders in the config like tasks files do. You have to use the whole path.
