### ISSUE TITLE
Publish to Open-VSX

### ISSUE THREAD

**Issue by dada513** [Sarrus1/sourcepawn-vscode#194]
## Feature description

What do you want to see added to the extension? I want to see it published to the [open-vsx](https://open-vsx.org) marketplace
How would it help you? Allow users of VSCodium and code-server to use the extension
How often would you use this feature? N/A

**Comment by Sarrus1** [comment]
Thanks for the suggestion, this has now been integrated to the CI.
Extension is available [here](https://open-vsx.org/extension/Sarrus/sourcepawn-vscode).
The namespace should be verified soon.

**Comment by dada513** [comment]
Many thanks!
