### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by robyzzz** [Sarrus1/sourcepawn-vscode#198]
Would be nice if extension had code folding. 
For example:
```c
//region abc
void my_function() {
    // ....
}

void my_function2() {
    // ....
}

void my_function3() {
    // ....
}
//endregion

//region something
void do_smt() {
    // ....
}

void do_smt2() {
    // ....
}
//endregion
```
so we can extend/hide regions and it hides multiple functions.

**Comment by Sarrus1** [comment]
[API Documentation](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding) for future reference
