### ISSUE TITLE
Formatter doing trouble

### ISSUE THREAD

**Issue by eyal282** [Sarrus1/sourcepawn-vscode#208]
I'm sorry if I made a mistake and somehow it's using another formatter ( though how because this is the only SP extension I use )

#define TEAM_CLASS  (% 1)(% 1 == 1 ? "Smoker" : (% 1 == 2 ? "Boomer" : (% 1 == 3 ? "Hunter" : (% 1 == 4 ? "Spitter" : (% 1 == 5 ? "Jockey" : (% 1 == 6 ? "Charger" : (% 1 == 7 ? "Witch" : (% 1 == 8 ? "Tank" : "None"))))))))
#define SELECT_KEY  (% 1)(% 1 == 1 ? IN_ATTACK2 : (% 1 == 2 ? IN_RELOAD : (% 1 == 3 ? IN_ZOOM : 0)))
#define PLAYER_KEYS (% 1)(% 1 == 1 ? "MELEE" : (% 1 == 2 ? "RELOAD" : (% 1 == 3 ? "ZOOM" : "None")))

This is how is formats the defines of l4d2_zcs.sp, which refuse to compile because of space between % and 1

**Comment by DeathScore13** [comment]
Just tried to copy

> `#define TEAM_CLASS (%1)(%1 == 1 ? "Smoker" : (%1 == 2 ? "Boomer" : (%1 == 3 ? "Hunter" : (%1 == 4 ? "Spitter" : (%1 == 5 ? "Jockey" : (%1 == 6 ? "Charger" : (%1 == 7 ? "Witch" : (%1 == 8 ? "Tank" : "None"))))))))
> #define SELECT_KEY (%1)(%1 == 1 ? IN_ATTACK2 : (%1 == 2 ? IN_RELOAD : (%1 == 3 ? IN_ZOOM : 0)))
> #define PLAYER_KEYS (%1)(%1 == 1 ? "MELEE" : (%1 == 2 ? "RELOAD" : (%1 == 3 ? "ZOOM" : "None")))`

somewhere and paste it in sp. Autoformatting with % from 1 separation did not happen. most likely the problem is not in this extension

**Comment by eyal282** [comment]
> Just tried to copy
> 
> > #define TEAM_CLASS (%1)(%1 == 1 ? "Smoker" : (%1 == 2 ? "Boomer" : (%1 == 3 ? "Hunter" : (%1 == 4 ? "Spitter" : (%1 == 5 ? "Jockey" : (%1 == 6 ? "Charger" : (%1 == 7 ? "Witch" : (%1 == 8 ? "Tank" : "None"))))))))
> > #define SELECT_KEY (%1)(%1 == 1 ? IN_ATTACK2 : (%1 == 2 ? IN_RELOAD : (%1 == 3 ? IN_ZOOM : 0)))
> > #define PLAYER_KEYS (%1)(%1 == 1 ? "MELEE" : (%1 == 2 ? "RELOAD" : (%1 == 3 ? "ZOOM" : "None")))
> 
> somewhere and paste it in sp. Autoformatting with % from 1 separation did not happen. Most likely the problem is not in this extension.

This is the only extension I installed. Then perhaps it's default extensions.

**Comment by GFearLose** [comment]
([Before formatting])
public Action : Event_Player_Spawn(Handle: event, String: event_name[], bool: dontBroadcast)
([After formatting])
public Action : Event_Player_Spawn(Handle
: event, String
: event_name[], bool
: dontBroadcast)
([The compiler reported an error])
error 001: expected token: ";", but found ":"
error 010: invalid function or declaration
error 021: symbol already defined: "Handle"
warning 215: expression has no effect
([compiler version])
v1.5.0.0
sourcdmod

**Comment by Sarrus1** [comment]
I have started working on a new formatter which you can find here:

https://github.com/Sarrus1/SPFormat

**Comment by Sarrus1** [comment]
All further issues regarding the formatter will be redirected to https://github.com/Sarrus1/SPFormat.
