### ISSUE TITLE
Does not read includes properly with custom sourcemod_home path

### ISSUE THREAD

**Issue by ghost** [Sarrus1/sourcepawn-vscode#21]
`sourcemod.inc` has these includes
![image](https://user-images.githubusercontent.com/75724044/114779992-a8700400-9d2b-11eb-8b0b-8c558be3605a.png)
I have it in a custom location other than the server
![image](https://user-images.githubusercontent.com/75724044/114780306-10264f00-9d2c-11eb-81ea-4506ec6304e7.png)
It can read from `sourcemod.inc`
![image](https://user-images.githubusercontent.com/75724044/114780538-64313380-9d2c-11eb-81b0-f3b8aaf79673.png)
But for example `LoadTranslations()` doesn't show up from `lang.inc` despite being in `sourcemod.inc`
![image](https://user-images.githubusercontent.com/75724044/114780919-dd308b00-9d2c-11eb-933d-ff4d7443a90d.png)

It only shows up if I use the server path `/tf/addons/sourcemod/scripting/include`, have `#include <lang>`, or if I open `lang.inc`.
Also happens with `sourcepawnLanguageServer.optionalIncludeDirsPaths`.

Thanks again for updating!

**Comment by Sarrus1** [comment]
What does your custom include folder's structure look like?
If you move the content of the include folder from `/tf/addons/sourcemod/scripting/include` to the new location, does it work?

**Comment by r9vRM** [comment]
It is just a copy of `/tf/addons/sourcemod/scripting/include`, so only `.inc`'s

**Comment by Sarrus1** [comment]
I'm having trouble replicating your issue:
> It only shows up if I use the server path /tf/addons/sourcemod/scripting/include, have #include <lang>, or if I open lang.inc.

 - What do you mean by "server" here?
 - When you say that it works if you open lang.inc, does this mean it works with `D:/Documents/TF2/...`?

**Comment by r9vRM** [comment]
What I mean by opening is having it on another window in VScode, and there is no difference with my `scripting/include` and `/tf/addons/sourcemod/scripting/include`, literally just copy pasted it to another location.
![image](https://user-images.githubusercontent.com/75724044/114904059-4c10f100-9dcc-11eb-80ca-2b1fbf72ef53.png)

**Comment by Sarrus1** [comment]
Alright I see, I think I know what's going on, will try to reproduce this.
