### ISSUE TITLE
Adding highlighting #if blocks 

### ISSUE THREAD

**Issue by DeathScore13** [Sarrus1/sourcepawn-vscode#210]
What do you want to see added to the extension?
Add highlighting **#if** blocks when moving the cursor (**#if**, **#else**, **#elseif**, **#endif**), because when there are many conditions, the code becomes difficult to read. And even better, automatically add **#endif** with a comment, where the beginning of the block will be indicated. This is in **Visual Studio** and I would really like to see it in your extension.
![image](https://user-images.githubusercontent.com/73132270/157492182-b8dbcb6c-2258-4fce-9f1a-75697d705d46.png)

How would it help you?
This will make writing code much easier for me and many users.

How often would you use this feature?
Is always.

**Comment by HolyHender** [comment]
Good idea!

**Comment by dran1x** [comment]
Genius!
