### ISSUE TITLE
Automatic parameters for forwards and callbacks

### ISSUE THREAD

**Issue by DeathScore13** [Sarrus1/sourcepawn-vscode#211]
What do you want to see added to the extension?
Add automatic input of parameters for declared forwards and callbacks. Yes, they can be copied from the popped up window, but this is inconvenient.

How would it help you?
Will speed up writing code for me and many other people.

How often would you use this feature?
Always.

**Comment by Sarrus1** [comment]
Hi,

This was implemented in #31, if I understand what youare asking for correctly.

**Comment by DeathScore13** [comment]
By the way, about speeding up writing code. where can I remove **// Content** when using quick loop creation? I have to erase it, which takes a little time, although I could press the "down" key and Enter.

**Comment by DeathScore13** [comment]
I would also like to forego the automatic */, because I use it to comment out large blocks of code, I have to erase it all the time.
I also noticed a strange feature highlighting when using this commenting method:
![image](https://user-images.githubusercontent.com/73132270/157994486-fd581db6-8969-4ab9-aadf-01bd125b57a8.png)

**Comment by Sarrus1** [comment]
> And I noticed strange highlighting when using this comment method:

This will be fixed when the new parser is ready, it's an issue with highlighting in the comments.

**Comment by Sarrus1** [comment]
> By the way, about speeding up writing code.Where can I remove // Content when using quick loop creation? I have to erase it, which takes a little time, although I could press the "down" key and Enter.

You can edit your own snippets, but enough people have complained about the //Content for me to remove it in the next release.
