### ISSUE TITLE
#define description

### ISSUE THREAD

**Issue by DeathScore13** [Sarrus1/sourcepawn-vscode#212]
## Feature description

What do you want to see added to the extension?
Maybe you just didn't add it, but I think it's a mistake that the extension thinks #define can only do one line. The \ character has always been used for hyphenation, but for some reason the extension breaks the demonstration on the first line.
![git1](https://user-images.githubusercontent.com/73132270/157974939-a8bd08cb-3c63-4192-b96d-c153c78920d9.png)
I would also like to see the function code in #define and description.
![git2](https://user-images.githubusercontent.com/73132270/157975092-6f0df576-d0b9-46e3-85c2-225706ce733b.png)
![git3](https://user-images.githubusercontent.com/73132270/157975108-a024519f-bd02-456b-a8be-f86efd91f38f.png)

How would it help you?
This will help me better navigate my own and other people's code. 

How often would you use this feature?
Always when I forget or don't know what this or that #define is responsible for :)

**Comment by Sarrus1** [comment]
Fixed in #221.
