### ISSUE TITLE
There is no mainpath set for this workspace

### ISSUE THREAD

**Issue by scorpius2k1** [Sarrus1/sourcepawn-vscode#239]
# Basic informations

- **OS:** [Linux]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

Apologies if this is due to my lack of understanding, new to VSCODE (VSCodium) and this extension. After installing, I keep getting the message "There is no mainpath set for this workspace. The extension will not work properly." It pops up every time I open an .sp file.

Screenshot: https://i.imgur.com/GCTJ0Wo.png

1. After installation, everything DOES work properly except I keep getting this error and not sure what to do. I have made no changes post-install.
2. What do I need to se as the main .sp for this to stop?

EDIT: FYI I first tried to contact directly via Discord link, https://discord.tensor.fr/ but it does not work.

**Comment by Sarrus1** [comment]
Hi,

I have updated the link to discord (thanks for letting me know!) and I have added more documentation regarding the main path, which you can see [here](https://github.com/Sarrus1/sourcepawn-vscode/wiki#setting-up-your-project).

Please let me know if there are parts that I can improve 👍
