### ISSUE TITLE
Unresponsive extenstion host & call stack error

### ISSUE THREAD

**Issue by Jackzmc** [Sarrus1/sourcepawn-vscode#24]
This randomly started happening a day ago where vscode has become basically useless due to everything ceasing to work, so today I checked the console and got this warning:
 WARN UNRESPONSIVE extension host, 'Sarrus.sourcepawn-vscode' took 95% of 5213.646ms, 
 
The profile is here: https://i.jackz.me/2021/04/SuperficialjUT8S.cpuprofile which reports that interpLine took 3,848 ms of that time.

I also got right after the warning this error:
```
workbench.desktop.main.js:2119 RangeError: Maximum call stack size exceeded
	at hidden (internal/errors.js:291:14)
	at Function.allocUnsafe (buffer.js:384:3)
	at tryCreateBuffer (fs.js:345:21)
	at Object.readFileSync (fs.js:379:14)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
	at Object.parse_file `(c:\Users\Jackz\.vscode\extensions\sarrus.sourcepawn-vscode-1.11.0\client\out\Providers\spParser.js:10:19)
```
After uninstalling this addon (and reinstalling old one) my vscode has started to work fine

**Comment by Sarrus1** [comment]
Hi, thanks for the letting me know.

This seems to be caused by a recursive logic error. Are you working on a big project by any chance? Please send an example so I can reproduce the error.

I'll try to fix this in a futur release anyways.

Please consider joining https://discord.tensor.fr to discuss the development of the extension 👍

**Comment by Poggicek** [comment]
> This randomly started happening a day ago where vscode has become basically useless due to everything ceasing to work, so today I checked the console and got this warning:
> WARN UNRESPONSIVE extension host, 'Sarrus.sourcepawn-vscode' took 95% of 5213.646ms,
> 
> The profile is here: https://i.jackz.me/2021/04/SuperficialjUT8S.cpuprofile which reports that interpLine took 3,848 ms of that time.
> 
> I also got right after the warning this error:
> 
> ```
> workbench.desktop.main.js:2119 RangeError: Maximum call stack size exceeded
> 	at hidden (internal/errors.js:291:14)
> 	at Function.allocUnsafe (buffer.js:384:3)
> 	at tryCreateBuffer (fs.js:345:21)
> 	at Object.readFileSync (fs.js:379:14)
> 	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
> 	at Object.parse_file `(c:\Users\Jackz\.vscode\extensions\sarrus.sourcepawn-vscode-1.11.0\client\out\Providers\spParser.js:10:19)
> ```
> 
> After uninstalling this addon (and reinstalling old one) my vscode has started to work fine

It's caused by a include including itself, this happens for example inside smlib's effects.inc.

**Comment by Jackzmc** [comment]
The thing is, I was coding the same project a few hours before this happened fine. I don't think I did any recursive includes, but some of my projects have a lot of includes.
Currently using the Drae's version for now and its working fine

**Comment by Sarrus1** [comment]
> I don't know what exactly changed that prompted this issue to appear

I made a change to the parsing of include files in 1.11.0:
> Improved the parsing of already parsed includes.

This might be the cause of your problem. Try reverting to 1.10.6 to fix the issue.
If you could also provide a sample repo of your project so that I'm able to reproduce the bug, that would be great

**Comment by Jackzmc** [comment]
https://github.com/jackzmc/sourcemod-plugins - the plugins I was working on was l4d2_feedthetrolls and possibly L4D2Tools. 

Downgrading to 1.10.6 does seem to fix the issue.

**Comment by Sarrus1** [comment]
Can you try commenting out [this line](https://github.com/Jackzmc/sourcemod-plugins/blob/df256d0e03c4339080ede3e370cfb5429089e128/scripting/include/smlib.inc#L19) with the latest version ? This seems to be the source of the problem.

**Comment by Jackzmc** [comment]
That include was not used anywhere in my code, even physically deleting the file and it's folder results in the same issue.

**Comment by Sarrus1** [comment]
Can you send me the project on discord ? https://discord.tensor.fr

**Comment by Jackzmc** [comment]
Well, I attempted to try updating it again and it seems to working fine now. 
Perhaps when I tested the updated latest version again the other day it didn't properly reload.

My issue seems to be fixed at this time,
