### ISSUE TITLE
Sub-include code error raises on main code

### ISSUE THREAD

**Issue by Zeisenx** [Sarrus1/sourcepawn-vscode#241]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

I'm sure had main path set.

# To Reproduce

I'm not sure actually what caused this error. some errors raises fine on sub-codes.

# Code to reproduce the behaviour

I sent full code files to Sarrus via Discord DM

# Expected behaviour

It should raise error on sub-file code

# Error messages

![image](https://user-images.githubusercontent.com/19303143/177929559-d9fcfec1-754d-4750-8831-aa703c4f72b3.png)

![image](https://user-images.githubusercontent.com/19303143/177929589-006da307-b485-4c7f-9193-e587a675a695.png)

![image](https://user-images.githubusercontent.com/19303143/177929606-584a143e-3eaa-4959-a39c-a7fbba78f71b.png)

![image](https://user-images.githubusercontent.com/19303143/177929932-0f10ee53-9a85-4529-a297-571f81289700.png)
(Actually raising error part on sub-include code line 127, but raises error on main code)
+ that code should be fixed
`ItemSlot slot = g_kvItemConfig.GetItemSlot(data);` 
to 
`ItemSlot slot = g_kvItemConfig.GetItemSlot(data.name);`

**Comment by Sarrus1** [comment]
So the issue occured when one would set the mainpath AFTER the first lint had ran, causing the initial error to persist.
