### ISSUE TITLE
Errors in temp.sp file.

### ISSUE THREAD

**Issue by Akllike** [Sarrus1/sourcepawn-vscode#249]
When writing code with errors, errors are shown in another temp.sp file. In the main file, these errors do not show. How to make errors show only in the main file?

![image](https://user-images.githubusercontent.com/50577139/181715300-0c77f6cf-84d1-4b38-91b0-d9d4e0fe3927.png)
![image](https://user-images.githubusercontent.com/50577139/181715410-6f35d6d1-8850-407e-9b4d-77ab2fd05541.png)

**Comment by Sarrus1** [comment]
Related to #248.
Will be fixed in rhe next release 👍

**Comment by Sarrus1** [comment]
Fixed in #250.
