### ISSUE TITLE
Can't seem to get the compiler to work

### ISSUE THREAD

**Issue by IntensityGit** [Sarrus1/sourcepawn-vscode#25]
When clicking the compile button I get the error "command 'sourcepawn-vscode.compileSM' not found"

I'm new to using VSCode so not entirely sure if I'm editing these correctly
This is my settings.json
![52qfp](https://user-images.githubusercontent.com/58851674/116765010-15b5b180-aa1b-11eb-8aec-c35dc5fd0039.png)

**Comment by Sarrus1** [comment]
Hi, thanks for submitting this isssue.

When this happens, can you please go to Help>Developper Tools and in the window that opens go to the console? You should be able to see a red error. Can you screenshot this and send it to me on [discord](https://discord.tensor.fr) ?

Also, it looks like you have several sourcepawn extensions installed, looking at your path. Try to disable the Linter extension and the Dreae's sourcepawn extension, as they are redundant with mine and might cause interferences.

Finally, as a temporary fix, try to rollback to a previous version of the extension while I figure this out, go to the marketplace and next to uninstall, click on the arrow>Install another version and select 1.10.6, which seems to work.

Thanks :)

**Comment by Sarrus1** [comment]
Closing this issue as it has been resolved over Discord.

It was due to an incorrect path in the options.
