### ISSUE TITLE
Extension Fails to Parse Certain Include Files

### ISSUE THREAD

**Issue by caxanga334** [Sarrus1/sourcepawn-vscode#274]
# Basic informations

- **OS:** Windows 10
- **VSCode version:** 1.73.1
- **Extension version:** 4.2.3

# Further Information

This extension fails to parse the include files of the [CBaseNPC](https://github.com/TF2-DMB/CBaseNPC) extension. So autocomplete doesn't include anything from those files.

# To Reproduce

1. Add the CBaseNPC include to a plugin.
2. Start writing any function or methodmap from the CBaseNPC extension.

# Code to reproduce the behaviour

```cpp
#include <sourcemod>
#include <cbasenpc>

#pragma newdecls required
#pragma semicolon 1

public void OnPluginStart()
{
    // start writing any function or methodmap from CBaseNPC
    // IE: CBaseNPC_GetNextBotOfEntity
    
}
```

# Expected behaviour

The autocomplete should list all available functions, methodmaps, enums, etc from the CBaseNPC extension.

# Error messages

No error message related to this extension appears.

# Possible cause of the issue

While testing things I found something. The CBaseNPC extention include files are written like this:

```cpp
#if !defined DEFNAME
#define DEFNAME

<CODE HERE>

#endif
```

While sourcemod default includes are written like this:

```cpp
#if defined DEFNAME
 #endinput
#endif
#define DEFNAME

<CODE HERE>
```

If I modify the CBaseNPC extension to follow the style of sourcemod default includes, autocomplete start working as normal.

The files are being parsed but it fails to read them properly because only the #define DEFNAME are listed for autocomplete.

![screenshot_vscode_autocomplete](https://user-images.githubusercontent.com/10157643/205055640-7834af7b-d7b4-48cf-b615-b49303eca80b.png)

**Comment by Sarrus1** [comment]
Thank you for reporting this.
The preprocessor needs some rework, and I am currently writing a new version of the parser over [here](https://github.com/Sarrus1/sourcepawn-lsp).

I will make sure to address this problem there 👍

**Comment by Sarrus1** [comment]
Assumed everything is fixed. Feel free to reopen if needed!
