### ISSUE TITLE
Compiling not working (linux)

### ISSUE THREAD

**Issue by HerrMagiic** [Sarrus1/sourcepawn-vscode#277]
# Basic informations

- **OS:** [Linux]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

Hey i have a problem with compiling .sp files on my linux system. Maybe my settings are wrong but i can figure out what causes the problem

# My settings.json

```json
{
    "sourcepawn.MainPath": "/home/orizon_surf/serverfiles/csgo/addons/sourcemod/scripting/",
    "sourcepawn.outputDirectoryPath": "/home/orizon_surf/serverfiles/csgo/addons/sourcemod/scripting/compiled/",
    "sourcepawn.SourcemodHome": "/home/orizon_surf/serverfiles/csgo/addons/sourcemod/scripting/include",
    "sourcepawn.SpcompPath": "/home/orizon_surf/serverfiles/csgo/addons/sourcemod/scripting/include/spcomp",
    "sourcepawn.availableAPIs": [

        {
            "name": "",
            "SMHomePath": "",
            "compilerPath": ""
        }
    ],
    "sourcepawn.MainPathCompilation": false,
    "sourcepawn.compilerOptions": [

        "-O2",
        "-v2"
    ],
    "sourcepawn.linterCompilerOptions": [
    
    ]
}
```

here is what happens when i click compile file:

![image](https://user-images.githubusercontent.com/70164539/209370185-44b2e2d4-fdba-4786-85de-dea4407f58be.png)

# Expected behaviour

That it will compile the selected file

# End
Thanks for helping

**Comment by HerrMagiic** [comment]
spcomp needed execute permissions

**Comment by Sarrus1** [comment]
Hello, glad you managed to fix the issue!

I think I know why the extension was not putputting any error message.

**Comment by HerrMagiic** [comment]
would be cool to add a permission missing message or something
