### ISSUE TITLE
How to disable Formatter

### ISSUE THREAD

**Issue by theelsaud** [Sarrus1/sourcepawn-vscode#284]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# Question
I have checkbox `Toggle the linter on or off`, but doesn't see checkbox for Formatter.
This is very important, because I have an old project on github, and when I start working with this repository, when I save the file, it shifts all the lines, which is not favorable for a commit.

How to disable this feature?

**Comment by Sarrus1** [comment]
Hi,

You probably have "editor.formatOnSave" set to `true` somewhere in your global settings.
Set it to `false` and you should be good to go.
See [this SO thread](https://stackoverflow.com/questions/61827206/vscode-disable-all-auto-formatting-on-save) for more details.

The extension only provides a formatter for VSCode to use. The extension does not control whether the formatter is enabled or not.
