### ISSUE TITLE
Third-party includes' functions don't get suggested if there is an sp file inside the include folder

### ISSUE THREAD

**Issue by Zabaniya001** [Sarrus1/sourcepawn-vscode#286]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest ( 5.3.1 )

# Further Information

If there is an `.sp` file inside the folder where the includes reside, the MainPath will default to whatever the .sp file inside it is and the extension won't properly work on the file you're actually working on.

# To Reproduce

1. Put a plugin file inside `SourcePawnLanguageServer.includesDirectories`
2. Try to use third-party includes in a plugin you're working on ( it can be any ).

**Comment by Sarrus1** [comment]
Hey, thanks for reporting this!
Ok it makes sense to not infer the mainpath from a file inside an includeDirectory.

Will fix asap!

In the meantime, you can manually set your mainpath to avoid this problem 👍
