### ISSUE TITLE
Include folder in project does not get recognised by the linter

### ISSUE THREAD

**Issue by Pheubel** [Sarrus1/sourcepawn-vscode#29]
Extension version: 1.11.3
SourcePawn: 1.10

When a `.inc` file is included is a sourcepawn file the linter will treat it as if the file can not be read. But the content of the `.inc` files do get properly linked and documentation still appears over methods from the `.inc` file, meaning that the script will still get compiled just fine due to the folder being included when the run button is hit.

Scenario:
![code image](https://user-images.githubusercontent.com/22686676/117209127-3d7b8f80-adf6-11eb-9589-e5e90df1cd7d.png)

Expected result:
No error warnings.

Actual result:
error warning: `fatal error 183: cannot read from file: "include/VSH2Utils.inc"`

**Comment by Sarrus1** [comment]
Hi thanks you for reporting this issue. Right now the extension doesn't support `.sp` files outside of the `scripting` folder, but I plan on making this available.
If you move the file in the scripting folder it should work.

**Comment by Sarrus1** [comment]
Closing this for now, as this file pattern is currently not supported by the extension.
