### ISSUE TITLE
Incorrect error markup on methodmap functions returning an array

### ISSUE THREAD

**Issue by KitRifty** [Sarrus1/sourcepawn-vscode#290]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** v5.3.3

# Further Information

Member functions of methodmaps that return a `char[]` is incorrectly marked as an error. However, global functions are correctly not marked as errors.

EDIT: It appears to happen regardless of type. I've updated the example code and title.

# Code to reproduce the behaviour

```sourcepawn
char[] MyStr() // this is fine
{
	char str[] = "this";
	return str;
}

int[] MyVec() // same as above
{
	int vec[] = { 0, 0, 0 };
	return vec;
}

float[] MyVec2() // same as above
{
	float vec[] = { 0.0, 0.0, 0.0 };
	return vec;
}

methodmap MyMethods
{
	public static char[] MyStr() // marked as error, specifically on the brackets
	{
		char str[] = "MyMethods";
		return str;
	}

	public static int[] MyVec() // same as above
	{
		int vec[] = { 0, 0, 0 };
		return vec;
	}

	public static float[] MyVec2() // same as above
	{
		float vec[] = { 0.0, 0.0, 0.0 };
		return vec;
	}
}
```

# Expected behaviour

No errors.

# Error messages

![image](https://user-images.githubusercontent.com/4492504/227096902-046799f2-acb2-41dc-81d1-4fcd3e029dc6.png)

**Comment by Sarrus1** [comment]
The original tree-sitter-sourcepawn seems to be inactive, I will use my fork for now.
