### ISSUE TITLE
`#endif` at EOF is marked as an error

### ISSUE THREAD

**Issue by KitRifty** [Sarrus1/sourcepawn-vscode#291]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** v5.3.3

# Further Information

An `#endif` at EOF is marked as an error (even if the syntax is correct). However, the error goes away if a comment or line break is added after it.

# Code to reproduce the behaviour

```sourcepawn
#define THIS_THING

#if defined THIS_THING

void MyFunc()
{
	PrintToServer("My function");
}

#endif
```

# Expected behaviour

No error.

# Error messages

![image](https://user-images.githubusercontent.com/4492504/227117494-8e94a8a4-9ed0-4167-96ee-8cd53b49e34e.png)

**Comment by Sarrus1** [comment]
The original tree-sitter-sourcepawn seems to be inactive, I will use my fork for now.
