### ISSUE TITLE
How to make friends with this extension with Error Lens?

### ISSUE THREAD

**Issue by IL0co** [Sarrus1/sourcepawn-vscode#292]
# Basic informations

- OS: [Windows]
- VSCode version: Latest
- Extension version: v5.3.5

# Problem
How to use this extension in tandem with [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens), so that all errors are displayed immediately in the code? And not only in the console (I would not want to see the console at all if it's Done)

**Comment by Sarrus1** [comment]
I have seen other people make this work without any configuration. Is the linter working without the Error Lens extension?
