### ISSUE TITLE
Incorrect error linting when using "#if" and "#else" within arrays(?)

### ISSUE THREAD

**Issue by KitRifty** [Sarrus1/sourcepawn-vscode#293]
# Basic informations

- **OS:** Ubuntu 22.04 (WSL)
- **VSCode version:** Latest
- **Extension version:** v5.3.6

# Further Information

Using a combination of `#if` and `#else` inside of arrays causes errors despite being valid SourcePawn code. This is problematic when it comes to some plugin ".inc" files in some `SharedPlugin` declarations and `REQUIRE_PLUGIN` is involved and `required` doesn't have a trailing comma.

# Code to reproduce the behaviour

```sourcepawn
// OK
int g_Test[] =
{
	1,
	2,
#if defined TEST_DEF
	3,
#else
	4,
#endif
}

// OK
int g_Test2[] =
{
	1,
	2,
#if defined TEST_DEF
	3,
#endif
}

// OK
int g_Test3[] =
{
	1,
	2,
#if defined TEST_DEF
	3
#endif
}

// OK
int g_Test4[] =
{
	1,
	2,
#if defined TEST_DEF
	3,
#else
	4
#endif
}

// ERROR (int_literal)
int g_Test5[] =
{
	1,
	2,
#if defined TEST_DEF
	3
#else
	4
#endif
}

// OK
char g_strTest[][] =
{
	"test1",
	"test2",
	"test3",
	"test4"
};

// OK
char g_strTest2[][] =
{
	"test1",
	"test2",
#if defined TEST_DEF
	"test3",
#endif
};

// OK
char g_strTest3[][] =
{
	"test1",
	"test2",
#if defined TEST_DEF
	"test3"
#endif
};

// OK
char g_strTest4[][] =
{
	"test1",
	"test2",
#if defined TEST_DEF
	"test3",
#else
	"test4",
#endif
};

// ERROR (symbol)
char g_strTest5[][] =
{
	"test1",
	"test2",
#if defined TEST_DEF
	"test3"
#else
	"test4"
#endif
};

// ERROR (symbol)
char g_strTest6[][] =
{
	"test1",
	"test2",
#if defined TEST_DEF
	"test3"
#else
	"test4",
#endif
};

// OK
public SharedPlugin __pl_test = {
	name = "test",
	file = "test.smx",
	required = 1,
};

// OK
public SharedPlugin __pl_test2 = {
	name = "test2",
	file = "test2.smx",
	required = 1
};

// OK
public SharedPlugin __pl_test3 = {
	name = "test3",
	file = "test3.smx",
#if defined REQUIRE_PLUGIN
	required = 1,
#else
	required = 0,
#endif
};

// ERROR (int_literal)
public SharedPlugin __pl_test4 = {
	name = "test4",
	file = "test4.smx",
#if defined REQUIRE_PLUGIN
	required = 1
#else
	required = 0
#endif
};
```

# Expected behaviour

No error

# Error messages

![image](https://user-images.githubusercontent.com/4492504/230741872-53cf1581-d31e-4149-bb2d-25f3f957e53c.png)

**Comment by Sarrus1** [comment]
Hey, thanks for reporting.

The parser cannot handle preprocessor statements very well as it does not have any context on the defines.

I am working on this, but until then, you can disable the syntaxlinter to make the error silent.

**Comment by Sarrus1** [comment]
Update on the progress in this PR: https://github.com/Sarrus1/sourcepawn-lsp/pull/26

**Comment by Sarrus1** [comment]
Fixed in https://github.com/Sarrus1/sourcepawn-lsp/pull/27.
