### ISSUE TITLE
SourcePawn Language Server crashes immediately.

### ISSUE THREAD

**Issue by relt-1** [Sarrus1/sourcepawn-vscode#296]
# Basic informations

- **OS:** Windows 11
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

Every time the plugin starts, the plugin language server crashes because of an invalid argument.

# To Reproduce

It seems to be an issue only for me, it happens when the plugins starts.

# Expected behaviour

The language server should start.

# Error messages

```
error: unexpected argument '-' found

Usage: sourcepawn_lsp.exe [OPTIONS]

For more information, try '--help'.
[Error - 4:46:56 PM] The SourcePawn Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 4:46:56 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:46:56 PM] SourcePawn Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

**Comment by Sarrus1** [comment]
Fixed in a0a2c503b89c6a40bd580feb4effc2f13aad9d09.
