### ISSUE TITLE
mainPath dosen't change as expected

### ISSUE THREAD

**Issue by stefanx111** [Sarrus1/sourcepawn-vscode#299]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest(5.3.8)

# Further Information

When I select a new file as main it remains the Workspace tab setting.

# To Reproduce

You can see it in this video. 

https://user-images.githubusercontent.com/60297289/233808760-6d3be279-1282-46f8-990c-7d897cd2e14d.mp4

# Code to reproduce the behaviour

# Expected behaviour

When I am in the Workspace folder and I want to select another file as main it dosen't change the mainPath.

# Error messages

**Comment by Sarrus1** [comment]
Note to myself: https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-multi-server-sample/client/src/extension.ts
