### ISSUE TITLE
Enchancement: Option to disable compile button

### ISSUE THREAD

**Issue by NullifidianSF** [Sarrus1/sourcepawn-vscode#3]
Thank you for your work 👍

**Comment by Sarrus1** [comment]
Will add this in the next release, I'm focusing on stability for now 👍

**Comment by NullifidianSF** [comment]
Ok cheers.

**Comment by Sarrus1** [comment]
Added in 586af1df98bb2faef1e7b35d7229ef1feeaf2677.
