### ISSUE TITLE
Multiline function arguments causing duplicate arguments in signature help provider

### ISSUE THREAD

**Issue by BoomShotKapow** [Sarrus1/sourcepawn-vscode#30]
If the include contains a function signature that has its arguments on a new line, it'll result in duplicate arguments in the hover.

Here's what the hover looks like: 
![Untitled](https://user-images.githubusercontent.com/75021396/117323243-561a9280-ae54-11eb-9b7f-cb1281cfc703.png)

And this is the function signature in [console.inc](https://github.com/alliedmodders/sourcemod/blob/47c050d5b636d71cecc62b665e3b97fc5d543f3b/plugins/include/console.inc#L399-L404):
![Capture](https://user-images.githubusercontent.com/75021396/117323533-9548e380-ae54-11eb-83a9-41f23c110b36.PNG)

If you put it all on one line, it works as intended.

Last example of messing around with it, just because:
![Untitled2](https://user-images.githubusercontent.com/75021396/117324307-49e30500-ae55-11eb-956c-71ee8820e97f.png)

**Comment by Sarrus1** [comment]
Thanks for letting me know, will be fixed in the next release, I suspect this is a trivial bug.

**Comment by BoomShotKapow** [comment]
> Thanks for letting me know, will be fixed in the next release, I suspect this is a trivial bug.

No problem and it typically is. Also, I'm curious, are you interested in receiving pull requests for features? Or would you prefer to just have someone submit a feature request and then you'll implement it yourself.

**Comment by Sarrus1** [comment]
Yes pull requests are welcome! What features do you have in mind? You can join our Discord at https://discord.tensor.fr to discuss this if you want 👍

**Comment by BoomShotKapow** [comment]
I didn't do much and I'm sure you could implement it in a much better way, but I just wanted a command to insert the function parameters of what was in the hover. It took me a bit longer than I'd like to admit, but then again JavaScript/TypeScript is completely foreign to me. And learning about LSP was interesting, it made more sense once I actually took the time to look into what it was.

But, if you're interested in my solution, I'll send it your way.

**Comment by Sarrus1** [comment]
So like a snippet for function arguments? That sounds like a nice feature to have, I'd be happy to take in a PR 👍 

I'm learning TypeScript as well through this project but if I find something I think is worth improving I'll be sure to let you know!
