### ISSUE TITLE
Use (Set current file as main) to update the smcompPath directory

### ISSUE THREAD

**Issue by ViniciusRed** [Sarrus1/sourcepawn-vscode#304]
# What do you want to see added to the extension?

* It would be great if (Set current file as main) updates if main from smcompPath directory

# How would it help you?

* This would help me to not have to configure every time I go to fix a plugin in a server folder using an external sftp or local server

# How often would you use this feature?

* daily or weekly by creating servers in different ways

**Comment by Sarrus1** [comment]
Closing as main path no longer exists.
