### ISSUE TITLE
Escaping quotes breaks SPL

### ISSUE THREAD

**Issue by MSWS** [Sarrus1/sourcepawn-vscode#305]
# Basic informations

- **OS:** Windows 11
- **VSCode version:** 1.79.0 (user setup)
- **Extension version:** 5.3.10

# To Reproduce
It appears that escaping quotes in functions seems to break the SPL Server / Code Auto completion.

Uncommenting the PrintToChatAll function causes auto complete to stop working, and quickly causes the SPL server to break.

# Code to reproduce the behaviour

https://paste.msws.xyz/?l=c#haste/pMa6TNu2

```
semanticTokensProviderStyling.ts:115 Semantic token with invalid length detected at lineNumber 14, column 7
warnInvalidLengthSemanticTokens @ semanticTokensProviderStyling.ts:115
notificationsAlerts.ts:42 The SourcePawn Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
c @ notificationsAlerts.ts:42
```

**Comment by Sarrus1** [comment]
This does not reproduce anymore, so I assume it was fixed when I revamped the lexer.
