### ISSUE TITLE
Reload only the plugin compiled

### ISSUE THREAD

**Issue by alexevladgabriel** [Sarrus1/sourcepawn-vscode#306]
# What do you want to see added to the extension?
It would be good to reload only the plugin compiled, instead of all plugins.
It can cause issues when working and crash the server.

# How would it help you?
-

# How often would you use this feature?
All time.

**Comment by maxijabase** [comment]
Aiming to tackle this down in #377

**Comment by maxijabase** [comment]
Can be closed
