### ISSUE TITLE
SourcePawn Language Server client: couldn't create connection to server.

### ISSUE THREAD

**Issue by F1F88** [Sarrus1/sourcepawn-vscode#310]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

vscode startup error：
> [Error - 15:36:37] SourcePawn Language Server client: couldn't create connection to server.
Launching server using command c:\Users\Yzg\.vscode\extensions\sarrus.sourcepawn-vscode-5.4.1\languageServer\sourcepawn_lsp.exe failed. Error: spawn c:\Users\Yzg\.vscode\extensions\sarrus.sourcepawn-vscode-5.4.1\languageServer\sourcepawn_lsp.exe ENOENT

Then the syntax prompt function fails.

May be the problem with the latest releases of https://github.com/Sarrus1/sourcepawn-lsp 0.10.12 about ?

# To Reproduce

Simply open the project folder using vscode

# Code to reproduce the behaviour

# Expected behaviour

# Error messages

**Comment by Sarrus1** [comment]
Yes, this is due to the latest release, I will fix it in the next hour, thanks for reporting 👍
