### ISSUE TITLE
Unknown Error in Format function

### ISSUE THREAD

**Issue by luckyweNda** [Sarrus1/sourcepawn-vscode#312]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information
When I use ```FormatEx()``` like this
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/ce6791a0-9619-459e-a6a5-d6e56cdc01b0)

it will shows an error, I dont know what this error means

After I delete the ```FormatEx()``` function, vscode will not shows the error
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/d5c1621e-2868-4f95-8b90-c0c420369543)

But I can compile this code although the plugin tells me there is an error
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/8029c29b-2003-4aca-915b-26fd5d23799f)

I use one line the error still occurs
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/2797c91b-e11b-401e-84d2-e20f7625878e)

When code is very simple, the ```Format``` behave correct
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/9526df5e-18e7-4355-8d02-90cfe07482db)

**Comment by Sarrus1** [comment]
Hi, thanks for reporting the issue!
Can you please post the code via text (whole project ideally) so that I can try to reproduce the error?

**Comment by luckyweNda** [comment]
> Hi, thanks for reporting the issue! Can you please post the code via text (whole project ideally) so that I can try to reproduce the error?
> 
> I assume that `POSTGRESQL_ROOT_DB` and `...SHOP_PLAYER` are defines, which can cause a problem for the parser if the preprocessor did not work properly.
> 
> You can also try the `Reveal preprocessed document (as seen by the server)` command (CTRL+SHIFT+P and type `Reveal preprocessed document (as seen by the server)`) This should show what the parser sees and the syntax error will be apparent.

test.inc
```
#define URL "url"
#define PLAYER "player"
```
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/27bd8ff3-793c-4adc-8a15-5b3f7edd4e60)

temp2.sp
```
#include <sourcemod>
#include <test>

#pragma semicolon 1
#pragma newdecls required

public void OnPluginStart()
{
    char url[256];
    Format(url, sizeof(url), "%s/%s,%d", URL, PLAYER, 5);
}
```
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/fd3d66ae-9b60-4b14-92a6-75ae381773f9)

ERROR:
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/dcad99a1-0f4f-47f1-81b3-a410b7bb8475)

Compile log
```
C:\Users\cialloo\sourcemodAPI\addons\sourcemod\scripting\spcomp.exe
c:\Users\cialloo\Desktop\backend\addons\sourcemod\scripting\temp2.sp 
-oc:\Users\cialloo\Desktop\backend\addons\sourcemod\plugins\temp2.smx 
-ic:\Users\cialloo\Desktop\backend\addons\sourcemod\scripting\include 
-ic:\Users\cialloo\Desktop\backend\addons\sourcemod\scripting 
-ic:\Users\cialloo\Desktop\backend\addons\sourcemod\scripting\include 
-iC:\Sourcemod\include 
-O2 -v2 

SourcePawn Compiler 1.11.0.6934
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

Code size:         3676 bytes
Data size:         2304 bytes
Stack/heap size:      16732 bytes
Total requirements:   22712 bytes

Done.
```
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/70629889/e9a3b3f2-84c1-411f-88ab-78bd15f08f65)
