### ISSUE TITLE
Plugin marketplace.visualstudio.com page broken image/gif examples

### ISSUE THREAD

**Issue by RB490** [Sarrus1/sourcepawn-vscode#337]
https://marketplace.visualstudio.com/items?itemName=Sarrus.sourcepawn-vscode#event-auto-completion

![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/13181077/d569a9ea-2bf5-4326-97a3-e14ba5180b90)

**Comment by Sarrus1** [comment]
Fixed in v6.0.1
