### ISSUE TITLE
Tab doesn't work

### ISSUE THREAD

**Issue by HolyHender** [Sarrus1/sourcepawn-vscode#34]
v1.11.5

Hello.
When I try to press TAB with this hint plate, the TAB just doesn't work. In the extension by Dreae, it works.
![image](https://user-images.githubusercontent.com/59821865/119217875-9fc2d880-baf6-11eb-81cc-40ebd591b91f.png)

**Comment by Sarrus1** [comment]
Hi, so if I understand correctly, tab should work in a string right? I'll see if I can fix this. But if you say it works with Dreae's extension there's no reason it won't.

Thanks for reporting this!

**Comment by Sarrus1** [comment]
Hi,
After investigating, this happens because of [this](https://github.com/Sarrus1/sourcepawn-vscode/pull/31#issuecomment-848100343).
Will try to see if there is a "fix".

**Comment by Sarrus1** [comment]
fixed in v1.12.0
