### ISSUE TITLE
macro cannot be parsed

### ISSUE THREAD

**Issue by ProjectSky** [Sarrus1/sourcepawn-vscode#340]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

# To Reproduce

* this code cause extension stop working (after IS_VALID_SURVIVOR)
```c
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>
#include <left4dhooks>

#define IS_VALID_CLIENT(%1) (%1 > 0 && %1 <= MaxClients)
#define IS_SURVIVOR(%1) (GetClientTeam(%1) == L4D_TEAM_SURVIVOR)
#define IS_VALID_INGAME(%1) (IS_VALID_CLIENT(%1) && IsClientInGame(%1))
#define IS_VALID_SURVIVOR(%1) (IS_VALID_INGAME(%1) && IS_SURVIVOR(%1))

public void OnPluginStart()
{
	for (int i = 1; i <= MaxClients; i++)
	{
		if (IS_VALID_SURVIVOR(i) && !IsFakeClient(i))
		{
			PrintToChat(i, "Hello World");
		}
	}
}
```

# Code to reproduce the behaviour

# Expected behaviour

# Error messages

**Comment by ProjectSky** [comment]
latest version seems to have fixed this issue

**Comment by Sarrus1** [comment]
Reopening the issue because even though the server does not crash anymore, the macro is still incorrectly expanded, see this commit for the failing test:

https://github.com/Sarrus1/sourcepawn-vscode/commit/8022f59e564160da84d3aefa5387409a274229aa
