### ISSUE TITLE
No longer able to compile .sp with 6.0.3 on macOS

### ISSUE THREAD

**Issue by kelvinthh** [Sarrus1/sourcepawn-vscode#344]
# Basic informations

- **OS:** [macOS 14 Sonoma (aarch64)]
- **VSCode version:** Latest
- **Extension version:** 6.0.3
- **SourceMod version:** 1.11 build 6863

# Further Information

I'm no longer able to compile any .sp file after auto updating to 6.0.3, and have to rollback to 6.0.2 in order to work, the compile button on the top right corner disappears on 6.0.3:

![6.0.3](https://i.imgur.com/HbnADef.png)
While in 6.0.2:
![6.0.2](https://i.imgur.com/Zo2gYqZ.png)

# To Reproduce

Update the extension from 6.0.2 to 6.0.3

# Code to reproduce the behaviour

# Expected behaviour

Should be able to compile via clicking the green play button at the top right corner.

# Error messages
I also tried manually run the compile command by F5 on 6.0.3:
![](https://i.imgur.com/S8teJHV.png)

**Comment by Sarrus1** [comment]
Does the linter work at all? It should try to call rosetta, just like the compile option.
I will try to repro in a few hours 👍

**Comment by Sarrus1** [comment]
> I also tried manually run the compile command by F5 on 6.0.3:

By the way, F5 is for debugging, you should use CMD+SHIFT+D 👍
