### ISSUE TITLE
Incorrect error message for struct array

### ISSUE THREAD

**Issue by gandor233** [Sarrus1/sourcepawn-vscode#346]
# Basic informations
OS: [Windows]
VSCode version: [v1.83.0]
Extension version: [v6.1.0]

# Code to reproduce the behaviour
```
enum struct TEST_STRUCT
{
    char str[256];
}
public void OnPluginStart()
{
    TEST_STRUCT sTestStructArray[1][1];
    Format(sTestStructArray[0][0].str, sizeof(sTestStructArray[][].str), "Why error?");
}
```

# Error messages
```(ERROR)```

![ScreenShot](https://github.com/Sarrus1/sourcepawn-vscode/assets/45251961/81dae410-7aa5-4928-9718-f463a7f83f00)

**Comment by Sarrus1** [comment]
This has been fixed in the grammar and merged in main. It is already fixed in the pre-release.
