### ISSUE TITLE
command 'sourcepawn-vscode.compileSM' not found

### ISSUE THREAD

**Issue by deff-dev** [Sarrus1/sourcepawn-vscode#35]
Hello, i have problem with create project/compile and another functions extension
i have OC ubuntu 20.04 and last version vscode
Message when i create sourcepawn project: "Command 'Project: SM Create Project' resulted in an error (command 'sourcepawn-vscode.createProject' not found)"

**Comment by Sarrus1** [comment]
Hi, 
This usually mean that the extension failed to start.
If you go in Help>Toggle Dev Tools and the in the "console" tab, you should see an error message.
Can you please copy it here? That would help me to debug the issue.
Also make sure your version of VSCode and your version of the extension are both up to date.

Thanks :)

**Comment by deff-dev** [comment]
![image](https://user-images.githubusercontent.com/44276186/119240371-bcdbc380-bb57-11eb-88ea-346e069e5e3e.png)

**Comment by Sarrus1** [comment]
Thanks for posting this. This doesn't help me however the error just says that the command failed to load without explaining why.

Can you please specify which version of the extension you're running on and which version of VSCode you're using?

Thanks in advance!

**Comment by deff-dev** [comment]
version of the extension:  1.11.5
version of VSCode: 1.56.2

**Comment by Sarrus1** [comment]
Alright so that's good.
Can you please join https://discord.tensor.fr so we can try to debug this? Others might have had the same bug.

Thanks !

**Comment by deff-dev** [comment]
I'm joined, my nick Deff

**Comment by Sarrus1** [comment]
Fixed on discord, files were not opened from a workspace.
