### ISSUE TITLE
Incorrect error messages related to disableSyntaxLinter

### ISSUE THREAD

**Issue by M60TM** [Sarrus1/sourcepawn-vscode#355]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# More Information

![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/96904513/2f7f2aa4-0afd-41d8-beb1-766d15bb8568)
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/96904513/b48558c5-334a-4377-bca8-34250349dad1)

**Comment by Sarrus1** [comment]
Fixed in the grammar [here](https://github.com/Sarrus1/tree-sitter-sourcepawn/commit/30ea5619e0a3c1726b779dcf1fb3ab05864dcf83).
Waiting for the feat/salsa branch to be merged to implement the fix.

Thanks for reporting!
