### ISSUE TITLE
macro/definition preview

### ISSUE THREAD

**Issue by Classes123** [Sarrus1/sourcepawn-vscode#361]
# What do you want to see added to the extension?
Preview of macro/definition replacements.

Screenshots (taken from clion):

![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/64929923/57776d52-f621-4f59-b465-7c9a0d175b76)

![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/64929923/c176e493-8637-4cca-8260-d16adb18de41)

# How would it help you?
Сurrent version gives little useful information about what I did wrong:
![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/64929923/dd515489-e954-4674-81fb-dbe9085c45b2)

# How often would you use this feature?
Always, I'm a macro lover.

**Comment by Sarrus1** [comment]
This is definitely on my radar! The c/cpp extension does that as well in VSCode.
The information is already there, it just has to be implemented.

This will be added in https://github.com/Sarrus1/sourcepawn-vscode/issues/362.

**Comment by Sarrus1** [comment]
<img width="517" alt="macro_expands_to_example" src="https://github.com/Sarrus1/sourcepawn-vscode/assets/63302440/b90a8210-eac5-483d-a3e7-33fd9247e705">

A sneak peek of what I was able to do in the feat/salsa branch.
