### ISSUE TITLE
The extension doesn't seem to work for me

### ISSUE THREAD

**Issue by Johnny2525** [Sarrus1/sourcepawn-vscode#37]
Hi!

VSCode: 1.56.2
Extension: 1.11.5

I just downloaded the extension and tried using it but...
The highlightning for me doesn't work
![image](https://user-images.githubusercontent.com/4202240/119500007-9d1aea00-bd67-11eb-8069-bf185faf83e3.png)

When I try to compile the opened .sp file it says "Not a .sp file, aborting"
![image](https://user-images.githubusercontent.com/4202240/119500029-a310cb00-bd67-11eb-8b97-c61d67375841.png)

My Config is:
![image](https://user-images.githubusercontent.com/4202240/119500231-dce1d180-bd67-11eb-9571-ea14f8d581b3.png)

I might be doing something wrong...But then I'd kindly ask for help.

**Comment by Sarrus1** [comment]
Hi,

The setting for sourcepawn.MainPath is incorrect, it should point to your .sp file.
So for instance: `"sourcepawn.MainPath": "C:/Me/MyProject/scripting/myproject.sp"`
Regarding the highlighting, I'm not sure what's going on, usually this is the most robust part.
Are you using a custom theme for vscode? That might break it.

For more discussion, feel free to join https://discord.tensor.fr

**Comment by Johnny2525** [comment]
Oh yeah I didn't think this through with highlightning I actually had another theme selected.
I fixed the MainPath but now on compile:
![image](https://user-images.githubusercontent.com/4202240/119504126-f9800880-bd6b-11eb-82d3-95dcf882615e.png)
![image](https://user-images.githubusercontent.com/4202240/119504141-fdac2600-bd6b-11eb-9462-f270269117cd.png)

**Comment by Johnny2525** [comment]
I've received help on Discord.
Everything is working now. Thanks a lot!

Resolution:
I left the MainPath setting empty [I am working on a single .sp file]
