### ISSUE TITLE
Add outputDirectoryPath as optional availableAPIs param

### ISSUE THREAD

**Issue by nikooo777** [Sarrus1/sourcepawn-vscode#379]
# What do you want to see added to the extension?
Similarly to how SPedit handled configurations, it would be nice if I could specify a custom `outputDirectoryPath` directory for each API definition.
Something like this:

```json
"sourcepawn.availableAPIs": [
        {
            "name": "SM-1.11",
            "includesDirectories": [
                "C:/path/to/sm_1_11/include",
            ],
            "spcompPath": "C:/path/to/sm_1_11/spcomp64.exe",
            "compilerArguments": [],
            "outputDirectoryPath": "C:/path/to/compiled_1_11/",
            "linterArguments": []
        },
        {
            "name": "SM-1.10",
            "includesDirectories": [
                "C:/path/to/sm_1_10/include",
            ],
            "spcompPath": "C:/path/to/sm_1_10/spcomp.exe",
            "compilerArguments": [],
            "outputDirectoryPath": "C:/path/to/compiled_1_10/",
            "linterArguments": []
        }
    ],
```

An alternative to adding support for this param would be adding support for variables such as %filename% or %basename% so that one could do the following:

```json
            "compilerArguments": [
                "-oC:/path/to/compiled_1_11/%filename%.smx"
            ],
```

# How would it help you?
I like to keep my plugins separated, if they were compiled with an older version of SM I'd want the plugin to be in that folder.
This is so that I can support older plugins that aren't necessarily compatible with the new APIs.

# How often would you use this feature?
I just migrated from Spedit (I was oblivious to this awesome extension!!!!) and I use it every time I'm writing plugins.

Thank you for your exceptional effort!

**Comment by maxijabase** [comment]
Will look into it!

**Comment by Sarrus1** [comment]
This was implemented, thanks @maxijabase !
