### ISSUE TITLE
Incorrect size highlighting.

### ISSUE THREAD

**Issue by HolyHender** [Sarrus1/sourcepawn-vscode#38]
Hello.
Highlighting the array size of the first declared variables doesn't work. v1.11.5
![image](https://user-images.githubusercontent.com/59821865/119645489-804de780-be37-11eb-917d-607232547b0f.png)

**Comment by Sarrus1** [comment]
Hi,

This should be fixed in the next release, you can test the beta build in the releases section of this repo :+1:

**Comment by Sarrus1** [comment]
Ah good catch, I know where this comes from!
