### ISSUE TITLE
Rename Symbol Missing

### ISSUE THREAD

**Issue by rjdXpxigYxNT** [Sarrus1/sourcepawn-vscode#394]
# Basic informations

- **OS:** [Windows] 10
- **VSCode version:** Latest
- **Extension version:** v7.2.8 (pre-release)

# Further Information

Switching to `Pre-Release v7.2.8` from `Release v7.1.0` causes the `Rename Symbol F2` to disappear from the right-click context menu.

**Comment by Sarrus1** [comment]
Thank you for reporting this.

Rename has not been implemented in this version yet, but it will be for the stable release 👍

I will close this issue once it is implemented.
