### ISSUE TITLE
[Suggestion] Customizable build paths

### ISSUE THREAD

**Issue by Pheubel** [Sarrus1/sourcepawn-vscode#46]
### What do you want to see added to the extension?
In the settings i would like to have the ability to change the output directory of a compiled script change so it would reflect the structure of the project directory. By telling the settings what the root is for the source files and root build path it could create a structured compiled script directory.

In the settings i would add two text fields for local paths:
build path: This will determine the root of all the compiled scripts. If left empty it would use the default behavior.
source path: This will determine the root of all script files in a project, when compiling to a custom build path it would exclude this path when constructing the directories for the compiled scripts. If left empty it would assume that the project root is the top level directory for the scripts.

Example: 
In the project root directory i have a folder called `src`, in this folder the source files related to the main plugin would reside, as example i have plugin "Main.sp". Inside this directory is a subdirectory called `subplugins` in here are plugins that rely and hook into the main plugin but are not essential for the main plugin, as example i have plugin "Modifier.sp".

The full (project local) paths would look as followed:
"src/Main.sp"
"src/subplugins/Modifiers,sp"

In the settings i would've set the following fields:
build path: "compiled"
source path: "src"

When i compile these two scripts it would build the plugins with the following (project local) paths:
"compiled/Main.smx"
"compiled/subplugins/Modifier.smx"

### How would it help you?
It would provide me with an opt-in way of managing my plugins. It keeps the organisation i put in to the script files while making a clear distinction between source scripts and compiled plugins. This makes it easier for users that browse my repository to directly grab the latest in dev version of a plugin/.

### How often would you use this feature?
This feature would see use in most of my plugins i will write, as i like to have a clear distinction between raw scripts and compiled code.

**Comment by Sarrus1** [comment]
Hi, thanks for suggesting this.

I suppose that a command to "hot-swap" the build and src path would be useful as well?
A right click to set the current file as the src for example?

**Comment by Pheubel** [comment]
> I suppose that a command to "hot-swap" the build and src path would be useful as well?
> A right click to set the current file as the src for example?

could you provide an example of how that would work?

**Comment by Sarrus1** [comment]
Yes, in the current version, if you right click inside a file, you have the option to "Set current file as main file", which automatically adds the current file to the `MainPath` setting.
I was thinking of doing something similar.

**Comment by Pheubel** [comment]
sounds like it could definitely be helpful.
