### ISSUE TITLE
[BUG] Highlighting doesn't work for precision formatting

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#49]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.56.2]
* **Extension version:** [v1.12.4]

## Further Information

`%5.2f` isn't highlighted in strings. `%f` and `%.2f` works fine.

## To Reproduce

- Write "%5.2f" in a file.

## Expected behaviour

`%5.2f` is highlighted as well.

## Error messages

No error.

**Comment by Sarrus1** [comment]
Fixed in v1.12.5
