### ISSUE TITLE
[BUG]Can't Compile

### ISSUE THREAD

**Issue by deff-dev** [Sarrus1/sourcepawn-vscode#55]
## Basic info

* **OS:** [Linux]
* **VSCode version:** [v1.57.1]
* **Extension version:** [v1.12.6]

## Further Information

When i want compile sp file, i have error:
fatal error 184: cannot write to file: "compiled//path/shop_buy_granade.smx"
![image](https://user-images.githubusercontent.com/44276186/122673852-25f83a80-d1db-11eb-95fc-230e9cdc193a.png)

**Comment by HolyHender** [comment]
это не баг, тебе нужно создать папку compiled вручную

**Comment by dran1x** [comment]
Post your `"sourcepawn.outputDirectoryPath"`

**Comment by Sarrus1** [comment]
@dran1x I've talked with @deff-dev on Discord and I think the next release will fix this issue. I'm waiting for them to test it 👍

The path was correct.

**Comment by Sarrus1** [comment]
@dran1x I've talked with @deff-dev on Discord and I think the next release will fix this issue. I'm waiting for them to test it 👍

The path was correct.

**Comment by dran1x** [comment]
Ah alright

**Comment by Sarrus1** [comment]
@deff-dev 
Hi again, I wasn't able to reproduce the issue on MacOS. I don't have a Linux VM ready to test this, however, if it works on MacOS, there is no reason it wouldn't run on Linux.

Please test the new version of the extension (v1.12.7) from the marketplace, which will be published in a few hours.

Thanks
