### ISSUE TITLE
[Suggestion] Add symbols to the VSCode Outline

### ISSUE THREAD

**Issue by Adrianilloo** [Sarrus1/sourcepawn-vscode#57]
Hi, 

I think adding SP symbols for the active file into the Outline would be cool.
Here's an example on another language (C, MySQL header):

![Captura](https://user-images.githubusercontent.com/15228896/122920046-3a663f80-d361-11eb-947d-52b47d6ea3c4.PNG)

Users could quickly see all functions, enums, global variables, etc. and navigate to them quickly (by clicking on them). What do you think?

Thanks.

**Comment by Sarrus1** [comment]
Hi, this seems to be a very neet feature, will definetly try to implement this. Right now, I'm focusing on smoothing out bugs and cleaning up the code, so I'll close this issue and move this to the project instead.

[https://code.visualstudio.com/api/extension-guides/tree-view](Link to the API for future reference)
