### ISSUE TITLE
[Suggestion] Inlcude local .inc files 

### ISSUE THREAD

**Issue by c43721** [Sarrus1/sourcepawn-vscode#62]
## Feature description

What do you want to see added to the extension?
I want to see the ability to set a custom folder in the project that holds `.inc` files for that specific project.

How would it help you?
I find it hard or difficult to understand *where* the `.inc` files should go, or if I need to include them at all. Including this feature would help with organizing projects and their direct dependencies.

How often would you use this feature?
I would use this each second if I had to say anything. There's really no comparison, it would make having per-project `.inc`  files much easier to manage while also giving the opportunity for people to download them, if needed.

I also see one more additional thought, that we could have the ability to add global includes (to the root sourcemod installation) and per-project includes. I think this would very much help people, especially someone who is doing SourceMod just to create simple plugins.

**Comment by dran1x** [comment]
I'm pretty sure everything you described here is already possible if you're using the latest version of course, in the extension settings you can use the following to set global include files for the sourcemod installation.

    "sourcepawn.SourcemodHome": "C:\\Data\\011\\include"
    "sourcepawn.SpcompPath": "C:\\Data\\011\\spcomp.exe"

Then secondly, you can use this for each workspace to add additional include folder paths, or if you want global too.

       "sourcepawn.optionalIncludeDirsPaths": [

       ]

Also, when compiling plugins with the extension it automatically includes any `.inc` file it finds in the include folder, as well as any custom location within the same folder path as shown here.
![image](https://user-images.githubusercontent.com/48390633/124054756-7f304d00-d9d7-11eb-9eac-5c7e552d59ca.png)

**Comment by Sarrus1** [comment]
I don't have anything to add to what @dran1x said, it's exactly what I was going to say, thanks you! 👍
