### ISSUE TITLE
CPU and RAM maximum load

### ISSUE THREAD

**Issue by BRU7U5** [Sarrus1/sourcepawn-vscode#63]
## Basic info

* **OS:** [Windows 10]
* **VSCode version:** [v1.58.2]
* **Extension version:** [v1.12.7]

## Further Information

After starting working with .sp files, VS Code starts running many SourcePawn Compiler processes (spcomp.exe), which leads to a CPU load of up to 100% and almost completely consumes RAM.

CPU: Intel Core i7 7700
RAM: 16GB

SourceMod 1.10

![issue](https://user-images.githubusercontent.com/36147249/127738294-8b46954b-6b5e-415d-98da-74d5e55653ca.jpg)

**Comment by Sarrus1** [comment]
Hi, thanks for reporting this.

I suspect that this comes from the linter, which never closes when the compile fails.

Are you working with many .sp files opened at the same time? Do you have MainPath set? And if not, are you compiling with the green arrow or vscode tasks?

**Comment by BRU7U5** [comment]
Hello!

### I suspect that this comes from the linter, which never closes when the compile fails.

> I tried to disable linter and after starting of compiling and receiving compilation error,  the process "spcomp.exe" doesn't have been closed. It led to a high CPU and RAM load.

### Are you working with many .sp files opened at the same time? Do you have MainPath set? And if not, are you compiling with the green arrow or vscode tasks?

> I working with single and many .sp files. In all cases it led to "hanging" a process and spam other "spcomp.exe" processes. I have MainPath set. I compiling it by calling context menu (Right Click) and clicking "SM Compile file".

P.S. _I noticed that the reason for this bug is precisely the erroneous compilation of the plugin. After a compilation error, the process spcomp.exe doesn't close. And during the subsequent compilation, it is created again. In some cases that are still unknown to me, it is created again. Because with 3-4 compilation attempts, there were already more than 10 non-closed processes in the processes list (as in the screenshot). But now I have found a temporary way to fix this problem - it is necessary to click the button with the image of a garbage can in the plugin compilation terminal (the lower VS Code window), which shuts down the terminal. But I'm not sure that this method helps 100% of the time.

**But, it seems to me that this is not so much a problem of your extension, as of the spcomp.exe. I tried to run it manually for the test with erroneous or unsuccessful compilations, which also led to the process hanging.**_

**Comment by Sarrus1** [comment]
The processes appearing when switching tabs are probably the linter.

I'm 99% sure spcomp **should** close itself after it was ran, wether or not the compile was successful. Are you using a stable version of spcomp? Maybe try to upgrade/switch to a stable version.

I don't have a windows PC with me atm so I won't be able to test this myself.

**Comment by BRU7U5** [comment]
> The processes appearing when switching tabs are probably the linter.
> 
> I'm 99% sure spcomp **should** close itself after it was ran, whether or not the compile was successful. Are you using a stable version of spcomp? Maybe try to upgrade/switch to a stable version.
> 
> I don't have a windows PC with me atm so I won't be able to test this myself.

Im using a stable build of SourceMod 1.10 git-6510

**Comment by Sarrus1** [comment]
Alright, in that case, can you try compiling by hand in a regular windows shell? To see if the process closes or not

**Comment by BRU7U5** [comment]
> Alright, in that case, can you try compiling by hand in a regular windows shell? To see if the process closes or not

Hm, tried to change SourceMod version to 1.10 git-6488 and its works fine. It seems that this was the problem. Sorry for bothering you.

**Comment by Sarrus1** [comment]
No problem, glad you figured it out 👍
