### ISSUE TITLE
[BUG] Include .sp files

### ISSUE THREAD

**Issue by authtern** [Sarrus1/sourcepawn-vscode#65]
![image](https://user-images.githubusercontent.com/70801321/128149540-149a63de-7fad-41d8-b774-81a11fb7b3bd.png)

**Comment by Sarrus1** [comment]
Is your test/test.sp file empty by any chance? This will throw a "can't read from file error" from the compiler.

**Comment by authtern** [comment]
I checked, so and so, my plugin which is compiled by a regular compiler is not compiled by this extension.

**Comment by authtern** [comment]
moved the folder to include, it works now


I didn't change it
command: `PS C:\Users\autht\Desktop\plugins> .'E:/link/git/1-10/compiler/spcomp.exe' 'c:\Users\autht\Desktop\plugins\test.sp' -o='c:\Users\autht\Desktop\plugins\compiled\test.smx' -i='E:/link/git/1-10/compiler/include' -i='c:\Users\autht\Desktop\plugins\/include' -O2 -v2`

**Comment by Sarrus1** [comment]
I see where this comes from, fixing right away, although I recommand using an include folder anyways, for clarity

Thanks for reporting

**Comment by authtern** [comment]
But the error remained, it cannot read functions from other connected plugins.
![image](https://user-images.githubusercontent.com/70801321/128160965-219c33ea-20f3-4ad8-836a-4bc6b8220d3a.png)
![image](https://user-images.githubusercontent.com/70801321/128161029-9f832804-f988-4df3-8966-a7bc4259733c.png)
![image](https://user-images.githubusercontent.com/70801321/128161090-047185cf-6747-4538-92bf-b23791c69050.png)
`but the compilation is successful`
![image](https://user-images.githubusercontent.com/70801321/128161206-9b41b5f8-6400-4e69-84a7-b571cf75011f.png)

**Comment by Sarrus1** [comment]
You have to go to the entry point file (EasyRanks.sp here) and right click on it, and click on `SM Set File as Main Path`.
This is necessary for projects with multiple .sp files.

**Comment by authtern** [comment]
Thank you, you been really helpful.
