### ISSUE TITLE
[Suggestion] Methodmap recognition on variable type

### ISSUE THREAD

**Issue by aleeperezz16** [Sarrus1/sourcepawn-vscode#68]
Detect the object handle methodmap on "new" keyword.
![image](https://user-images.githubusercontent.com/53284952/128400937-614cfa1e-e09d-45d0-878c-abd95e8fe446.png)
This is an example where "new Menu()" doesn't show the methodmap initialization intellisense.

![image](https://user-images.githubusercontent.com/53284952/128401145-ad3ebe18-a3a9-4a67-b5ec-8cb860db2f2a.png)
This is another example where the "menu" object doesn't recognize its own methodmap functions but others.

Also, if i type "menu." no intellisense is popped unless I start typing.

**Comment by Sarrus1** [comment]
Proper methodmap support is on the way, I've just finished refactoring the autocompletion code, I _should_ have everything I need to start implementing this without issues.

**Comment by dran1x** [comment]
> Proper methodmap support is on the way, I've just finished refactoring the autocompletion code, I _should_ have everything I need to start implementing this without issues.

🙏🙏🙏

**Comment by Sarrus1** [comment]
@dran1x @aleeperezz16 
This has been implemented in 2.0.0
![Example](https://cdn.discordapp.com/attachments/335290997317697536/874702199270285312/Example2.gif)
