### ISSUE TITLE
[BUG] Autocompletion won't work for some natives

### ISSUE THREAD

**Issue by xSL0W** [Sarrus1/sourcepawn-vscode#71]
## Basic info

* **OS:** Windows
* **VSCode version:** v1.59.0
* **Extension version:** 2.0.0

## Further Information

some functions won't autocomplete and go to definition is not working.
example:
KickClient()

## To Reproduce

Steps to reproduce the behaviour:
just write KickClient() in vscode
https://prnt.sc/1mlli7h

## Expected behaviour
to show the explained function and parameters

## Error messages
https://paste.ofcode.org/wHBzubrhAysixNzJcVsuk9

**Comment by Sarrus1** [comment]
Thanks you for linking the error, the parser seems to be confused at some point.

I wasn't able to replicate this with the latest production release (v2.0.0)
Try to download v2.0.1 from the [releases page](https://github.com/Sarrus1/sourcepawn-vscode/releases/v2.0.1).
This will make sure you have the proper build.
