### ISSUE TITLE
[BUG] Intellisense not showing correctly

### ISSUE THREAD

**Issue by aleeperezz16** [Sarrus1/sourcepawn-vscode#72]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.59.0]
* **Extension version:** [v2.0.0]

## Further Information

If you create a variable that stores a methodmap globally, when you use it on any function, intellisense doesn't work.
Also, some defines, functions from your project and global variables that are stored on other files but your main file, don't get recognized on the intellisense.

## To Reproduce

Steps to reproduce the behaviour:
1. Create a project and put .sp files apart from the main file.
2. Create variables/defines/functions
3. Include the .sp files on your main -> #include "path/file.sp"
4. Start using functions/variables/defines from these files

**Comment by Sarrus1** [comment]
Just to make sure, did you set the `MainPath` setting?

**Comment by aleeperezz16** [comment]
Yes, i did. Twice to be sure

**Comment by Sarrus1** [comment]
So it seems like, when you add a define to a sub-.sp file, it won't suggest anything in the main.sp file...
I'm working on a fix
