### ISSUE TITLE
[BUG] Problems with the highlight

### ISSUE THREAD

**Issue by HolyHender** [Sarrus1/sourcepawn-vscode#73]
## Basic info

* **OS:** [Windows]
* **Extension version:** [v2.0.0]

Привет, крутое обновление, но я нашел парочку багов.

## The function type is highlighted as a function
![image](https://user-images.githubusercontent.com/59821865/129077833-db544af5-9e21-4a2c-b8d2-e30ffd893420.png)
## Problems with the highlight
![image](https://user-images.githubusercontent.com/59821865/129078027-c34d57e8-2662-444b-b502-be2b85bf1911.png)
![image](https://user-images.githubusercontent.com/59821865/129078288-6109eb6c-f3da-44ee-a573-166afb2fd2a1.png)
![image](https://user-images.githubusercontent.com/59821865/129078726-cd80b0a7-e548-48f6-8619-3182c95c6d50.png)

**Comment by HolyHender** [comment]
![image](https://user-images.githubusercontent.com/59821865/129163982-022f4151-147d-4bb8-aed7-1635a5a34472.png)

**Comment by Sarrus1** [comment]
Thanks for reporting this.
Regarding the first issue with the define highlighting, it looks like you are using a beta build, because this was fixed a few days ago before the push to production

Try to install the extension by downloading it from the releases page on GitHub.
