### ISSUE TITLE
[BUG] Error highlighting and intellisense parsing errors

### ISSUE THREAD

**Issue by aleeperezz16** [Sarrus1/sourcepawn-vscode#78]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.59.0]
* **Extension version:** [v2.0.1]

## Further Information

Hey, just found some simple bugs on highlighting like this:
![image](https://user-images.githubusercontent.com/53284952/129396836-3cfc6912-9e45-45f2-9616-717ec13f9890.png)

Also, I've found that ConVar methodmap is not parsed correctly. If you type 'variable.' on the Intellisense you get non methodmap functions like this:
![image](https://user-images.githubusercontent.com/53284952/129397079-f94edc2a-3055-4347-96a2-e1405ada0297.png)
![image](https://user-images.githubusercontent.com/53284952/129397106-ab42d3f1-f143-41a5-8f53-d4f4a24545b2.png)

To add, I wish if you can also highlight 'struct' keyword:
![image](https://user-images.githubusercontent.com/53284952/129397229-579f72ae-08fa-4c8e-a8ad-6b177a951c7e.png)

**Comment by aleeperezz16** [comment]
About the methodmap issue; ArrayList, ArrayStack and StringMap don't get outside methodmap functions on the Intellisense BUT they don't fully get all the methodmap methods on the list.
![image](https://user-images.githubusercontent.com/53284952/129397686-9cd5facd-1082-4483-9474-e53187268c3f.png)
There are missing like 4-5 methods

**Comment by Sarrus1** [comment]
This should be fixed in v2.0.2
