### ISSUE TITLE
[BUG] Inconsistent highlighting

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#79]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.59.0]
* **Extension version:** [v2.0.1]

## Further Information

2 problems. https://imgur.com/a/1J9MtO7
For the "of" highlighting bug, this also happen with "this" and a few other keywords that I can't quite remember.

## Expected behaviour

"Handle" should be the same color, "of" should not be colored differently

## Error messages

None

**Comment by Sarrus1** [comment]
This should be fixed in v2.0.2
