### ISSUE TITLE
Make linter works with sub-files

### ISSUE THREAD

**Issue by Kxnrl** [Sarrus1/sourcepawn-vscode#8]
in sub-file editor, get too many error spam.

**Comment by Sarrus1** [comment]
I will likely disable the linter all together for sub files, as it's just the sourcepawn compiler under the hood, and it obviously doesn't work for sub files alone.
Or get the "main" .sp file and compile from here.

**Comment by Kxnrl** [comment]
I think we can use magic comment in top of subfile. make linter to parse the main file.

**Comment by Sarrus1** [comment]
Yes that would work, will had that in the next release :+1:

**Comment by Sarrus1** [comment]
@Kxnrl  
Partially fixed in 04d96b8eeb857545f792bda89c574bcbb227dfd1.

In a future release, I'll make it so that the linter only checks the primary file and thus provides errors for the sub files as well.
