### ISSUE TITLE
[BUG] Errors and warnings point to the wrong file using "Set file as main"

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#84]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.59.0]
* **Extension version:** [v2.1.1]

## Further Information

Clicking on errors/warnings on secondary files redirects to the main file instead of secondary files.
However, `public` functions have no warning/error (intended?) and `static` functions work properly.

## To Reproduce

[bug.zip](https://github.com/Sarrus1/sourcepawn-vscode/files/6987987/bug.zip)
By setting `bug.sp` as main file, warnings from `anotherfile.sp` will be shown as `bug.sp` warnings instead.

## Expected behaviour
Clicking on errors/warnings on secondary files redirects to right files.

## Error messages
None

**Comment by Sarrus1** [comment]
![Image](https://cdn.discordapp.com/attachments/831994555263221810/876784896176177162/Capture_decran_2021-08-16_a_14.09.29.png)

This is the compiler's fault, the extension is parsing the errors correctly.

IIRC this has been fixed in SM 11.
