### ISSUE TITLE
[ENHANCEMENT] Duplicate suggestions with forwards

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#92]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.59.0]
* **Extension version:** [v2.2.2]

## Further Information

Functions are suggested twice if there is already a forward function included and an implemented public function.

## To Reproduce
Example: [bug.zip](https://github.com/Sarrus1/sourcepawn-vscode/files/7009580/bug.zip)

Two `OnChangeSomething` suggestions appear while typing `OnChangeAnotherThing`.

## Expected behaviour

Only one suggestion should appear.

## Error messages
None.

**Comment by Sarrus1** [comment]
I'm aware of this issue, and I have yet to make a choice as to how to solve it:
- Either I leave it like this, which is a little bit confusing at best.
- Or, I add a filter when providing the completions, which looks for duplicates.

The second solution would add an O(nlog(n)) complexity algorithm to the completion provider which would make it slower, especially for large projects.

I still don't know which one is best...

Also, there's the problem of Hover and GoToDefinitions
In the case of `OnPluginStart` for example, which one should GoToDefinition point to? The forward inside the .inc file, or the overdefinition itself in the .sp file?

To me it makes sense to point to the .sp for the GoToDefinitions and to the .inc for the Hover, as it's the best of both world, what are you going to do with the forward anyways?
Maybe the ideal scenario would be to implement [this](https://code.visualstudio.com/api/references/vscode-api#LocationLink)

What do you think?

**Comment by zer0k-z** [comment]
I don't know much about vscode, but I noticed while reading C++ code, go to definition can open a mini window which you can choose where you can read it from, and autocompletion shows a small window which include the source file, like this:
![image](https://user-images.githubusercontent.com/61156310/130027463-2e6d89b9-7ea3-478e-9fb5-63ef154c206f.png)

**Comment by Sarrus1** [comment]
![Example](https://cdn.discordapp.com/attachments/831994555263221810/878623545071140894/Sans_titre.png)

The extension already provides the name of the file, but checkout the following build
